name: Go Release

on:
  push:
    tags:
      - 'v*'  # Runs only when a tag starting with "v" (e.g., v1.0.0) is pushed

jobs:
  build:
    name: Build & Release Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]  # Builds for Linux, Windows, and macOS
        goarch: [amd64, arm64]  # You can add 'arm64' if needed
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Set up Build Environment
        run: echo "Building for ${{ matrix.goos }}-${{ matrix.goarch }}"

      - name: Build Binary
        run: |
          mkdir -p build
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/myapp-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: myapp-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/myapp-${{ matrix.goos }}-${{ matrix.goarch }}
